apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: mes-gateway
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    hostname: mes.karsten.com
    port: 80
    protocol: HTTP